[project]
name = "folio-auto-renew"
version = "0.0.1"
description = "An early preview of the Umbrellaleaf automatic renewals"
authors = [
    {name = "Katherine Bargar",email = "kbargar@fivecolleges.edu"},
]
dependencies = ["folioclient[orjson]>=1.0.0"]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "Apache-2.0"}

[project.urls]
Homepage = "https://github.com/Five-Colleges-Incorporated/folio-auto-renew"
"Bug Tracker"= "https://github.com/Five-Colleges-Incorporated/folio-auto-renew/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
package-dir = "src"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib"]
asyncio_mode = "auto"

[tool.coverage.run]
branch = true
include = ["src/**"]

[tool.ty.rules]
blanket-ignore-comment = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unsupported-dynamic-base = "warn"
[tool.ty.analysis]
strict-literal-narrowing = true
strict-generic-narrowing = true

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = ["FBT", "D105", "FIX002", "TD002", "TD003", "COM812", "CPY001"]
pydocstyle.convention = "google"
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "S", "INP001", "N813", "PLC0415", "PLR2004"]
[tool.ruff.lint.flake8-annotations]
mypy-init-return = true

[tool.pdm.scripts]
test-quick = "python -m pytest -vv -k 'not Integration' {args}"
test.composite = ["rm -f .coverage", "python -m coverage run -m pytest -vv {args}", "python -m coverage report"]
lock.composite = ["rm -f pylock.toml", "pdm lock --python=3.10", "pdm lock --lockfile pylock.maximal.toml --python=3.14", "pdm lock --strategy direct_minimal_versions --lockfile pylock.minimal.toml --python=3.10"]
test-install.composite = ["pdm sync --lockfile=pylock.minimal.toml", "pdm sync --lockfile=pylock.toml"]

[dependency-groups]
lint = [
    "ruff==0.16.2",
    "ty==0.0.69",
    "pre-commit-hooks==6.0.0",
]
test = [
    "pytest==9.1.1",
    "pytest-cases==3.10.1",
    "pytest-asyncio==1.4.0",
    "coverage==7.15.4",
]
